# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Renderer_config = debug
  Test_config = debug
endif
ifeq ($(config),release)
  Renderer_config = release
  Test_config = release
endif

PROJECTS := Renderer Test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Renderer:
ifneq (,$(Renderer_config))
	@echo "==== Building Renderer ($(Renderer_config)) ===="
	@${MAKE} --no-print-directory -C Renderer/Renderer -f Makefile config=$(Renderer_config)
endif

Test: Renderer
ifneq (,$(Test_config))
	@echo "==== Building Test ($(Test_config)) ===="
	@${MAKE} --no-print-directory -C Test/Test -f Makefile config=$(Test_config)
endif

clean:
	@${MAKE} --no-print-directory -C Renderer/Renderer -f Makefile clean
	@${MAKE} --no-print-directory -C Test/Test -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Renderer"
	@echo "   Test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"